name: Pop

on:
  workflow_dispatch:
    inputs:
      IMAGES_TO_SCAN:
        type: string
        required: true
        description: A comma separated list of images to scan.

jobs:
  pop:
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
